# -*- coding: utf-8 -*-
"""NumPy: análise numérica eficiente com Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZVXSSCwfva9lU-T8veeNr7eavvj5Kkl
"""

import numpy as np

url = 'https://raw.githubusercontent.com/alura-cursos/numpy/dados/apples_ts.csv'

7*12+3 # 7 anos de informação vezes 12 meses do ano mais 3 primeiros meses de 2020 = 87.


# Explicando os parenteses do np.range:
# 1º coluna da tabela | Resultado da soma acima [87] +1 porque ele não vai até o ultimo valor, que é a quantidade de elementos da tabela. | Valor do incremento para que ele pule de 1 em 1 pela tabela.
np.arange(1, 88, 1) # Gera uma sequencia de valores.

dado = np.loadtxt(url, delimiter=',',usecols=np.arange(1, 88, 1))
# print(dado) 

dado.ndim # Dados em 2 dimensões.
# print(dado.ndim)

dado.size # Quantidade de elementos.
# print(dado.size)

dado.shape # 6 linhas e 87 colunas.
# print(dado.shape)

dado_transposto = dado.T # Transforma linhas em colunas e colunas em linhas.
# print(dado_transposto)


