# -*- coding: utf-8 -*-
"""Pandas: conhecendo a biblioteca - Desafio 1: bora praticar?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpeH_f2_pcedGUwz7g7QUsz6Z6Sl16F8

# Desafio 1: bora praticar?

Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar algumas análises utilizando um arquivo csv diferente: [alunos.csv](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv).

1) Importe o arquivo alunos.csv e armazene seu conteúdo em um DataFrame Pandas.

2) Visualize as primeiras 7 linhas do DataFrame e as 5 últimas.

3) Confira a quantidade de linhas e colunas desse DataFrame.

4) Explore as colunas do DataFrame e analise os tipos dos dados presentes em cada coluna.

Extra: Calcule algumas estatísticas descritivas básicas dos dados do DataFrame (média, desvio padrão, etc). Dica: pesquise pelo método describe.
"""

# Resolvendo o exercicio:

# 1)
import pandas as pd
url_dos_dados = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
alunos = pd.read_csv(url_dos_dados)

# 2.0)
alunos.head(7)

# 2.1
alunos.tail(5)

# 3)
alunos.shape

# 4)
alunos.info()

# 4.1)

alunos['Nome']

# 4.2)
alunos[['Idade', 'Notas']]

# 4.3)
alunos.dtypes

# 4.4)
alunos.describe()

# O método describe() é uma das funções mais úteis do Pandas para a análise exploratória de dados.
# Essa função é usada para calcular algumas estatísticas descritivas básicas dos dados em um DataFrame
# ou em uma coluna específica de um DataFrame.