# -*- coding: utf-8 -*-
"""Projeto_Python_Data_Science - NUNCA APAGAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xHCzysw89k0TOhEbGeQEsNcbjdCRNao

# Python para Data Science

Notebook para o curso de Python para Data Science publicado na plataforma da [Alura](https://www.alura.com.br/)

# Introdução ao Python

Vamos conhecer o Python, nosso ambiente de estudo e também faremos nosso primeiro código nessa linguagem!

## Google Colaboratory

Já aprendemos o que é o [Python](https://www.python.org/) agora vamos aprender a utilzar o [Google Colaboratory](https://colab.research.google.com/) e programar em um notebook.

Vamos testar algumas funções dessa ferramenta.

**`>>> Use essa célula para mover <<<`**
"""

print('Olá Mundo!')

"""## Olá mundo!

Vamso conhecer mais como funciona o ambiente interativo de um notebook. Para isso vamos executar nosso primeiro comando em Python: [`print()`](https://docs.python.org/3/library/functions.html#print)
"""

print('Olá Mundo!')

print('Olá Mundo!')

print('Olá Mundo!')

"""# Manipulando dados

Vamos aprender sobre as variáveis no python, como elas são declaradas e utilizadas além de conhecer outros comandos dentro do Python. :D

## Variáveis

Em Data Science nós trabalhamos com vários dados e informações, então é essencial saber trabalhar com variáveis.

Criamos uma variável no python através da atribuição de um valor a ela.

Para fazer isso, colocamos o nome da variável um sinal de igual (`=`) e o valor que queremos atribuir
"""

idade = 1

idade

print(idade)

idade



"""Nomes que **não** podemos definir para variáveis:

- **Nomes que começam com números**
  - Exemplos: `10_notas`, `2_nomes_casa`, etc.
- **Palavras separada por espaço**
  - Exemplos: `Nome escola`, `notas estudantes`, etc.
- **Nomes de funções do Python**
  - Exemplos: `print`, `type`, etc.

> Letras maiúsculas e minúsculas vão gerar diferentes variáveis. A varíavel `idade` é diferente de `Idade` que por sua vez também é diferente de `IDADE`:
``` Python
idade = 1
Idade = 2
IDADE = 3
_idade = 4
_idade_ = 5
print(idade, Idade, IDADE, _idade, _idade_)
1 2 3 4 5
```

## Tipos de variáveis

Cada variável contém uma classe especifica quanto ao tipo de objeto que ela está se referenciando. Essas classes vão ser diferentes a partir do tipo de dado que nós atribuimos a uma variável.

Para saber a classe de cada elemento usamos a função [`type()`](https://docs.python.org/3/library/functions.html#type)
"""









"""Em um conjunto de dados escolares podemos ter vários tipos de informações. Digamos que tenhamos acesso à ficha de dados do aluno *Frabicio Daniel* como transformamos ela em variáveis no Python?

#### Ficha:

- Nome: Fabricio Daniel
- Idade: 15 anos
- Media do semestre: 8,45
- Situação de aprovação: Verdadeira (aprovado)
"""



"""## Variáveis numéricas

Entre os tipos de dados numéricos vamos nos focar no tipo `inteiro` e `float`.

Temos uma tabela de informação de empregos quanto ao cargo, quantidade de pessoas empregadas e o salário correspondente:

|Cargo | Quantidade | Salário|
|---|---|---|
|Segurança | 5 | 3000 |
|Docente | 16| 6000|
|Diretoria| 1 |12500|

Precisamos trabalhar com esses dados fornecendo:

- A quantidade total de empregados;
- A diferença entre o salário mais baixo e mais alto; e
- A média ponderada da faixa salarial da escola.
"""

q_seguranca = 5
s_seguranca = 3000

q_docente = 16
s_docente = 6000

q_diretoria = 1
s_diretoria = 12500







"""## Strings

Strings são caracterizada por ter um conjunto de caracteres formando um texto.

Strigs podem ser criadas ao atribuirmos a uma variável um dado que esteja entre aspas simples (`'`) ou aspas duplas (`"`)
"""

'isso é uma string'

"""As variáveis textuais contém vários métodos que nos ajudam a formatar strings. Métódos podem ser executados ao definirmos um objeto seguindo a seguinte estrutura:

```
objeto.metodo()
```

Existem métodos que não necessitam dos `()`, é preciso verificar a documentação de cada caso.

---
**Situação:**

Recebemos uma variável com o nome de uma professora da escola para inserimos no cadastro. No entanto, precisamos tratar esse texto antes de inserirmos no sistema
"""

texto = '  Geovana Alessandra dias Sanyos '

"""O objetivo final é que o nome esteja da seguinte forma:

```
'GEOVANA ALESSANDRA DIAS SANTOS'
```

### [`str.upper()` ](https://docs.python.org/3/library/stdtypes.html#str.upper)
Converte uma string para maiúsculas
"""

texto = 'GEOVANA ALESSANDRA DIAS SANTOS'
texto_maiusculo = texto.upper()
print(texto_maiusculo)

"""### [`str.lower()`](https://docs.python.org/3/library/stdtypes.html#str.lower)
Método converte uma string para minúsculas.
"""

texto = 'GEOVANA ALESSANDRA DIAS SANTOS'
texto_minusculo = texto.lower()
print(texto_minusculo)

"""### [`str.strip()`](https://docs.python.org/3/library/stdtypes.html#str.strip)
Método remove os espaços em branco do início e do fim de uma string.
"""

texto = "   GEOVANA ALESSANDRA DIAS SANTOS   "
texto_sem_espacos = texto.strip()
print(f"'{texto_sem_espacos}'")

"""### [`str.replace(antigo, novo)`](https://docs.python.org/3/library/stdtypes.html#str.replace)

Método substitui todas as ocorrências do texto "antigo" na string por "novo"
"""

texto = "GEOVANA ALESSANDRA DIAS SANTOS"
novo_texto = texto.replace("GEOVANA ALESSANDRA DIAS SANTOS", "Geovana Alessandra Dias Santos")
print(novo_texto)

"""### Observações

1. Os métodos retornam uma **tranformação**, não a executam no texto!

2. Além disso, podemos acumular a execução de métodos.
"""

texto

"""Para que seja executada a transformação nós podemos atribuir às saídas das transformações à variável"""

texto = texto.upper()
texto

"""## Coletando dados

Em algumas aplicações precisamos coletar valores da pessoa usuária do nosso projeto. Em python conseguimos coletar dados de usuário através do comando [`input()`](https://docs.python.org/3/library/functions.html#input).

Para fazer essa coleta podemos atribuir essa função à uma variável.
"""

teste = input('Testando, insira algo: ')

recebendo = teste
recebendo

"""Existem funções para conversão de valores:

- Inteiros: [`int(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#int)
- Float: [`float(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#float)
- String: [`str(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#func-str)
- Booleano: [`bool(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#bool)
"""

ano_entrada = input('Escreva o ano de ingresso do(a) estudante: ')

type(ano_entrada)

ano_entrada = int(input('Escreva o ano de ingresso do(a) estudante: '))

type(ano_entrada)

"""Buscaremos apresentar melhor agora o resultado que obtivemos da transformação. Nós conseguimos formatar e apresentar o nosso resultado misturando strings com valores não textuais.

Para fazer isso usamos a estrutura de formatação `f` com strings.
"""

nota_entrada = float(input('Digite a nota do teste de ingresso: '))

"""# Estruturas condicionais

## `IF` e `ELSE`

O `if` e `else` são duas estruturas condicionais. O `if` executará o bloco de comando caso a condição colocada for **verdadeira**. O `else` é um caso em que a condicional de `if` seja **falsa**.

O `if` é uma palavra-chave em Python que significa "se". Ele é usado para formar uma estrutura condicional, que permite que você verifique se uma determinada condição é verdadeira ou falsa e, em seguida, execute um bloco de código específico dependendo do resultado da verificação. A sintaxe para usar o `if` é:



```
if condição:
    # faça algo
```
"""

if 10 > 5:
  print('Verdadeiro')

"""Já o `else` em Python é usada em conjunto com a palavra-chave `if` para formar uma estrutura condicional. A sintaxe para usar o `else` é:

```
if condição:
  # código caso seja verdade
else:
  # código caso seja falso
```

O `else` é executado quando a condição verificada pelo `if` é avaliada como `False`.

---
**Situação:**

Receberemos a média de estudantes e precisamos de um algoritmo que execute a análise e decida se esse estudante está **Aprovado** ou Reprovado, mostrando uma mensagem do resultado. Para ser aprovado, a média precisa ser igual ou superior à 6.0.
"""

media = float(input('Digite a média: '))

"""Agora a nossa instituição de ensino lançou uma nota oficial que pessoas que tenham média entre 4.0 e 6.0 podem fazer os cursos de **Recuperação** nas férias para poder recuperar a nota.

Então podemos agora fazer um conjunto de `if`s para que possamos estruturar essa nova condição.
"""

media = float(input('Digite a média: '))

"""Notemos que em casos com 3 situações como esse precisamos definir bem nossas condições. Pois foi feita uma construção com `else` no final, ele irá considerar apenas a alguma condicional para ser o caso **falso** podendo resultar em duas (ou mais) execuções.

Por exemplo:
"""

media = float(input('Digite a média: '))

"""## `ELIF`

O `elif` é uma palavra-chave em Python que significa "senão, se" e pode ser considerado uma união do `else` com um `if`. Ela é usada em conjunto com a palavra-chave `if` para formar uma estrutura condicional encadeada.

A sintaxe para usar o `elif` é:

```
if condição1:
    # faça algo
elif condição2:
    # faça outra coisa
elif condição3:
    # faça mais alguma coisa
else:
    # faça algo diferente
```

O `elif` permite que você verifique várias condições de forma encadeada, economizando espaço em seu código. Se a primeira condição for avaliada como `False`, o interpretador Python avaliará a próxima condição no `elif`. Isso continuará até que uma condição seja avaliada como `True` ou até que o `else` seja atingido. Se nenhuma das condições forem avaliadas como `True`, a execução do código do `else` será iniciada.

Vamos usar o mesmo caso anterior:
"""

media = float(input('Digite a média: '))

"""## Operadores

Durante a construção de comandos por vezes precisamos de uma elaboração maior de da expressão condicional, necessitando que alguns operadores lógicos estejam integrados.

### `AND`, `OR`, `NOT`

Os operadores lógicos `and`, `or` e `not` são usados para combinar expressões lógicas em Python. Eles são usados frequentemente em conjunto com o `if` para criar estruturas condicionais mais complexas.

- `AND` é usado para verificar se duas condições são verdadeiras. A expressão lógica¹ `x and y` é avaliada como `True` apenas se **ambas as condições `x` e `y` forem verdadeiras**, e como `False` caso contrário.

- `OR` é usado para verificar se pelo menos uma das condições é verdadeira. A expressão lógica `x or y` é avaliada como `True` **se pelo menos uma das condições `x` ou `y` for verdadeira**, e como `False` se ambas forem falsas.

- `NOT` é usado para **negar uma condição**. A expressão lógica not x é avaliada como True se a condição x for falsa, e como False se a condição x for verdadeira.

¹ Uma expressão lógica é uma declaração que pode ser avaliada como verdadeira ou falsa. Ela é composta por operandos lógicos² e operadores lógicos³, que são usados ​​para combinar várias expressões lógicas em uma única expressão.

² Os operandos lógicos são os elementos que são comparados ou avaliados em uma expressão lógica. Eles são geralmente valores verdadeiros ou falsos, mas também podem ser expressões lógicas mais complexas. Em Python, os operandos lógicos são os valores `True` e `False`.

³ Os operadores lógicos são os símbolos ou palavras-chave que são usados ​​para combinar várias expressões lógicas em uma única expressão. Em Python, os operadores lógicos são `and`, `or` e `not`, bem como as palavras-chave `if`, `elif` e `else`.
"""

# AND
# O operador and retorna True se ambas as condições forem verdadeiras.

a = 10
b = 5

# Ambas as condições precisam ser verdadeiras
if a > 5 and b < 10:
    print("Ambas as condições são verdadeiras")

# OR
# O operador or retorna True se pelo menos uma das condições for verdadeira.

a = 10
b = 15

# Apenas uma das condições precisa ser verdadeira
if a > 5 or b < 10:
    print("Pelo menos uma condição é verdadeira")

# NOT
# O operador not inverte o valor lógico. Se a expressão for True, not a tornará False e vice-versa.

a = 10

# Inverte a condição
if  not a < 5:
    print("A condição foi invertida e agora é verdadeira")

# IF
# A palavra-chave if é usada para executar um bloco de código se uma condição for verdadeira.

a = 10

if a > 5:
    print("A é maior que 5")

# ELIF
# A palavra-chave elif significa "else if" e permite verificar múltiplas condições.

a = 10

if a < 5:
    print("A é menor que 5")
elif a == 10:
    print("A é igual a 10")

# Exercicio envolvendo todos os operadores lógicos :)

idade = 20
altura = 1.75
peso = 70

# Verifica se a pessoa é maior de idade, tem altura maior que 1.7 e não é muito leve
if idade >= 18 and altura > 1.7 and not peso < 60:
    print("A pessoa atende a todos os requisitos.")
elif idade < 18 or altura <= 1.7:
    print("A pessoa não atende aos requisitos de idade ou altura.")
else:
    print("A pessoa não atende aos requisitos.")

"""### `IN`

É usado para verificar se um elemento está presente em uma lista, tupla ou outra variável de conjunto. A expressão `x in y` é avaliada como `True` se o elemento `x` estiver presente na variável de conjunto `y`, e como `False` caso contrário.

Podemos verificar isso com variáveis de texto.

---

**Situação:**

Na escola foi passada uma lista com nomes de estudantes que foram aprovados por média no semestre, mas é preciso verificar se alguns nomes estão nessa lista para verificar se os dados estão corretos.

A lista distribuida pode ser observada abaixo:

```
lista = 'José da Silva, Maria Oliveira, Pedro Martins, Ana Souza, Carlos Rodrigues, Juliana Santos, Bruno Gomes, Beatriz Costa, Felipe Almeida, Mariana Fernandes, João Pinto, Luísa Nascimento, Gabriel Souza, Manuela Santos, Thiago Oliveira, Sofia Ferreira, Rafael Albuquerque, Isabella Gomes, Bruno Costa, Maria Martins, Rafaela Souza, Matheus Fernandes, Luísa Almeida, Beatriz Pinto, Mariana Rodrigues, Gabriel Nascimento, João Ferreira, Maria Albuquerque, Felipe Oliveira
'
```

Os nomes que precisam ser verificados são os seguintes:

```
nome_1 = 'Mariana Rodrigues'
nome_2 = 'Marcelo Nogueira'
```
"""

lista = 'José da Silva, Maria Oliveira, Pedro Martins, Ana Souza, Carlos Rodrigues, Juliana Santos, Bruno Gomes, Beatriz Costa, Felipe Almeida, Mariana Fernandes, João Pinto, Luísa Nascimento, Gabriel Souza, Manuela Santos, Thiago Oliveira, Sofia Ferreira, Rafael Albuquerque, Isabella Gomes, Bruno Costa, Maria Martins, Rafaela Souza, Matheus Fernandes, Luísa Almeida, Beatriz Pinto, Mariana Rodrigues, Gabriel Nascimento, João Ferreira, Maria Albuquerque, Felipe Oliveira'
lista

nome_1 = 'Mariana Rodrigues'
nome_2 = 'Marcelo Nogueira'

if nome_1 in lista:
    print(f"{nome_1} está na lista.")
else:
    print(f"{nome_1} não está na lista.")

if nome_2 in lista:
    print(f"{nome_2} está na lista.")
else:
    print(f"{nome_2} não está na lista.")

"""# Estruturas de repetição

Quando temos que executar um mesmo bloco de comandos por várias vezes não é muito interessante fazer isso à mão.

Imaginemos a situação de termos que coletar e imprimir a média de duas notas de **3 estudantes**:
"""

nota_1 = float(input('Digite a 1° nota: '))
nota_2 = float(input('Digite a 2° nota: '))

print(f'Média: {(nota_1+nota_2)/2}')

"""Agora imaginemos uma situação em que não são apenas 3 estudantes, mas sim 100 estudantes. Não seria interessante repetir o mesmo código por 100 vezes, mas sim **executar o mesmo código 100 vezes**.

Essa repetição conseguimos construir com laços de repetição!

## `WHILE`

O laço `while` é uma estrutura de controle de repetição em Python que permite executar um bloco de código repetidamente enquanto uma determinada condição é verdadeira. Sua estrutura é:



```
while condição:
    # bloco de código
```

Vamos construir um exemplo com um contador de 1 até 10.
"""

contador = 1

while contador <= 10:
    print(contador)
    contador += 1

"""Agora vamos coletar as notas e médias de cada aluno dentro do while. Faremos um exemplo com 3 médias."""

# Inicializando as variáveis
aluno = 1
total_alunos = 3

while aluno <= total_alunos:
    print(f"\nAluno {aluno}:")

    # Coletando as 3 notas
    nota1 = float(input("Digite a 1ª nota: "))
    nota2 = float(input("Digite a 2ª nota: "))
    nota3 = float(input("Digite a 3ª nota: "))

    # Calculando a média
    media = (nota1 + nota2 + nota3) / 3

    # Exibindo a média
    print(f"Média do Aluno {aluno}: {media:.2f}")

    # Passando para o próximo aluno
    aluno += 1

"""## `FOR`

O laço `for` é um tipo de estrutura de controle de fluxo em Python que permite iterar sobre um conjunto de elementos. A sua estrutura é:



```
for elemento in conjunto:
    # código a ser executado para cada elemento
```

O laço for itera sobre cada elemento do conjunto especificado e executa o bloco de código dentro do laço para cada elemento. Quando o laço chega ao final do conjunto, ele é interrompido e o programa continua a execução após o laço.

O conjunto pode ser gerado com a função [`range()`](https://docs.python.org/3/library/functions.html#func-range). Que é uma função capaz de gerar uma sequência de números inteiros. A estrutura dessa função é:

```
range(inicio, fim, passo)
```

Segundo a documentação, o `range()` gera uma sequência de números inteiros a partir do valor do parâmetro `inicio` até o valor do parâmetro `fim`, de acordo com o valor do parâmetro `passo`. Se `inicio` não for especificado, o valor padrão é 0. Se `passo` não for especificado, o valor padrão é 1.

Vamos fazer o mesmo contador `while` agora com `for`.

while True:
  print(contador)
  contador += 1
"""



"""# Estruturas de dados

Um conjunto de elementos é uma coleção de itens, que são armazenados juntos de maneira organizada. Alguns exemplos de conjuntos de elementos em Python são listas, strings e dicionários.

## Listas

As listas podem armazenar uma coleção de itens em ordem. Eles são delimitados por colchetes `[]` e os itens são separados por vírgulas.

Elas também podem armazenar qualquer tipo de item, incluindo números, strings, objetos e outras listas. Elas também podem armazenar itens de tipos de dados diferentes juntos em uma única lista.
"""

lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]

"""As listas são organizadas em Python porque **cada elemento da lista tem um índice que indica sua posição na lista**. Os índices começam em 0 e vão até o tamanho da lista menos 1.

Temos então 5 elementos com índices variando de 0 a 4, ordenadamente:

```
#             [0]           [1]   [2]   [3]    [4]
lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]
```

Em Python temos também os índices **negativos** que se iniciam no último elemento com o valor de `-1` e depois avancam no universo dos negativos até chegar no 1° elemeno:

```
#             [-5]         [-4]  [-3]  [-2]   [-1]
lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]
```

Conseguimos selecionar separadamente cada elemento através de seus respectivos índices. Colocando o nome da lista e em seguida o índice a ser selecionado.
"""

lista[0]

lista[1]

lista[-1]

lista[-2]

"""Uma forma mais dinâmica de trabalhar item por item de uma lista é utilizando um laço for para leitura elemento a elemento."""

for elemento in lista:
  print(elemento)

"""A nota `8.0` de Fabricio Daniel precisa ser ajustada pois ganhou 2 pontos em sua ultima nota por fazer um trabalho de turma. Então é necessária fazer uma troca no valor do índice `3` de `8.0` para `10.0`."""

lista[3] = 10.0
lista

"""conseguimos calcular a média do aluno a partir dos dados que temos"""

media = (lista[1] + lista[2] + lista[3])/3
media

"""## Manipulação de listas

As listas são muito úteis em Python porque permitem armazenar e acessar uma coleção de itens de maneira organizada e rápida. Elas também oferecem muitos métodos úteis para manipular os itens armazenados, como adicionar, remover, classificar e pesquisar elementos.

#### Quantidade de elementos

Usamos a função [`len()`](https://docs.python.org/3/library/functions.html#len) para descobrimos a quantidade de elementos de um conjunto.
"""

len(lista)

"""#### Partição

A partição de listas por indexação em Python é uma técnica muito útil para selecionar um subconjunto de elementos de uma lista. Ela é feita usando a sintaxe `lista[inicio:fim]`, onde `inicio` é o índice do primeiro elemento a ser incluído na partição e `fim` é o índice do primeiro elemento a ser excluído da partição.
"""

lista[1:4]

lista[1:3]

lista[:3]

lista[3:]

lista[:]

"""#### [`append()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=of%20list%20objects%3A-,list.append(x),-Add%20an%20item)

Adiciona um elemento ao final da lista.
"""

lista.append(media)
lista

"""#### [`extend()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=list.extend(iterable))

Adiciona vários elementos ao final da lista.

Adicionaremos as notas `[10.0,8.0,9.0]` na lista do Fabricio Daniel
"""

lista.extend([10.0,8.0,9.0])
lista

"""*Isso não é possivel ser feito com o* `append`."""

lista.append([10.0,8.0,9.0])
lista

"""#### [`remove()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=append(x).-,list.remove(x),-Remove%20the%20first)

Remove um elemento específico da lista.
"""

lista.remove([10.0,8.0,9.0])
lista

"""## Dicionário

Os dicionários são um tipo de estrutura de dados que armazenam pares de *chave-valor*. Eles são delimitados por chaves `{}` e os pares *chave-valor* são separados por vírgulas.

```
dicionário = {chave: valor}
```

A **chave** é um elemento único que identifica um valor no dicionário, enquanto o **valor** é o item que é armazenado para a chave. As chaves e os valores podem ser de **qualquer tipo de dado**.

Os dicionários são úteis para armazenar e acessar dados de maneira organizada e rápida. Eles são um tipo de conjunto de elementos em Python, pois armazenam uma coleção de itens.
"""

dicionario = {'chaves_1' :1,
              'chaves_2' :2}

dicionario

"""---
**Situação:**

Vamos criar um conjunto de dados com informações de matricula de um estudante. Os dados são os seguintes:

- matricula: 2000168933
- dia de cadastro: 25
- mês de cadastro: 10
- turma: 2E
"""

cadastro = {
    'matricula': 2000168933,
    'dia': 25,
    'mes': 10,
    'turma': '2E'
}

cadastro

cadastro['matricula']

cadastro['turma']

"""É possível substituir os valores dentro de uma chave. Por exemplo, recebemos a informação que a turma do estudante que cadastramos foi trocada para `'2G'` e agora precisamos trocar o valor da chave `'turma'`."""

cadastro['turma'] = '2G'
cadastro

"""Podemos também adicionar outros dados ao dicionário. Vamos adicionar a informação de modalidade de ensino, nosso estudante atuará inicialmente em modalidade EAD.

Então iremos definir uma chave chamada `'modalidade'` e o valor `'EAD'`.
"""

cadastro['modalidade'] = 'ead'
cadastro

"""## Aprofundando em dicionários

#### [`pop()`](https://python-reference.readthedocs.io/en/latest/docs/dict/pop.html)
Remove um item de um dicionário e o retorna.
"""

cadastro.pop('turma')

cadastro

"""#### [`items()`](https://python-reference.readthedocs.io/en/latest/docs/dict/items.html)
Retorna uma lista de pares chave-valor do dicionário.
"""

cadastro.items()

"""#### [`keys()`](https://python-reference.readthedocs.io/en/latest/docs/dict/keys.html)
Retorna uma lista das chaves do dicionário.
"""

cadastro.keys()

"""#### [`values()`](https://python-reference.readthedocs.io/en/latest/docs/dict/values.html)
Retorna uma lista dos valores do dicionário.
"""

cadastro.values()

"""### Leitura de valores com `for`"""

for chave in cadastro.keys():
  print(cadastro [chave])

for valores in cadastro.values():
  print(valores)

for chave, valor in cadastro.items():
  print(chave, valor)