# -*- coding: utf-8 -*-
"""Pandas I/O: trabalhando com diferentes formatos de arquivos - (EXERCICIO 2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ky2MFuGcGbqSo_-hC3DC_k-QhNsYvnip

# **Desafio: lendo dados de outro link**

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Nós temos um link do [Google Planilhas](https://docs.google.com/spreadsheets/d/1kB2ai8KsGyINA_DMhW5VRZJtEbLUegNbpddUTB3LI5M/edit?gid=0#gid=0) que contém dados importantes sobre as emissões de gás carbônico pelo mundo. O conjunto de dados foi obtido no [Kaggle](https://www.kaggle.com/datasets/koustavghosh149/co2-emission-around-the-world?resource=download) e consiste em emissões de CO2 per capita de todos os países do mundo de 1990 a 2019.

Neste desafio, a sua função é efetuar a leitura desse link do Google Planilhas e depois salvar o DataFrame obtido no formato CSV. Pronto(a) para começar?
"""

import pandas as pd

# planilha = 'https://docs.google.com/spreadsheets/d/1dI1jqIxlUfaitXRxaxYXuse1SX3Da1dVjyqxnqs1arg/edit?usp=sharing'
sheet_id = '1dI1jqIxlUfaitXRxaxYXuse1SX3Da1dVjyqxnqs1arg'
sheet_name = 'CO2Emissions'
url_CO2 = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

dados_CO2 = pd.read_csv(url_CO2)
dados_CO2.head()

# Salvando em um DataFrame:
dados_CO2.to_csv('dados_CO2.csv', index=False, sep=';')

# Testando se deu certo:
pd.read_csv('dados_CO2.csv', sep=';')