# -*- coding: utf-8 -*-
"""Pandas I/O: trabalhando com diferentes formatos de arquivos - (EXERCICIO 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rzz7mQfUvW4I6HNvaCeEgPFveWCLK4PA

# Desafio: lendo uma tabela de uma página web

<p>Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.</p>

Vanessa é uma cientista de dados que está realizando algumas análises com dados ambientais. Ela está desenvolvendo um projeto para avaliar o impacto ambiental das atividades humanas em diferentes países do mundo, mas para isso precisa das estimativas populacionais desses países. Ao pesquisar na internet, encontrou uma tabela de estimativas populacionais em um artigo da página [Wikipédia](https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o).

<p>Assim como Vanessa, seu desafio é obter um DataFrame da tabela que contém as informações do número de habitantes de cada país.</p>
"""

import pandas as pd

dadospaises = '/content/Ex4.html'

dataframe_paises = pd.read_html(dadospaises)

dataframe_paises

dataframe_paises[0].to_csv('dataframe_paises', index=False)

dataframe_paises = pd.read_csv('dataframe_paises')

dataframe_paises.head()

# Condicional para sempre remover uma coluna Unnamed sem nome/index especifico
if 'Unnamed: 0' in dataframe_paises.columns:
  dataframe_paises = dataframe_paises.drop(columns=['Unnamed: 0'])

dataframe_paises