# -*- coding: utf-8 -*-
"""Desafio: hora da prática - AULA 1 (Python para Data Science: trabalhando com funções...).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTNhZKFIUGP-M6e5jAz_n6Qf6db3A2Hm
"""

!pip install matplotlib==3.7.1

import numpy as np

import random
lista = [8, 12, 54, 23, 43, 1, 90, 87, 105, 77]
print(f"Número escolhido: {random.choice(lista)}")

import random

numero_sorteado = random.randrange(100)
print(f"Número sorteado: {numero_sorteado}")

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
resultado = pow(num1, num2)
print(f"{num1} elevado a {num2} é {resultado}")

import random

participantes = int(input("Quantos participantes há no sorteio? "))
sorteado = random.randrange(1, participantes + 1)
print(f"O número sorteado é: {sorteado}")

import random

nome = input("Digite seu nome: ")
token = random.randrange(1000, 9999, 2)
print(f"Olá, {nome}, o seu token de acesso é {token}! Seja bem-vindo(a)!")

import random

frutas = ["maçã", "banana", "uva", "pêra", "manga", "coco",
          "melancia", "mamão", "laranja", "abacaxi", "kiwi", "ameixa"]
salada = random.sample(frutas, 3)
print(f"As frutas escolhidas foram: {salada}")

import math

numeros = [2, 8, 15, 23, 91, 112, 256]
for numero in numeros:
    raiz = math.sqrt(numero)
    if raiz == int(raiz):
        print(f"A raiz quadrada de {numero} é {int(raiz)} e é inteira.")

import math

raio = float(input("Digite o raio do jardim em metros: "))
area = math.pi * pow(raio, 2)
preco = 25 * area
print(f"O preço para cobrir o jardim circular será de R$ {preco:.2f}")