# -*- coding: utf-8 -*-
"""Pandas: selecionando e agrupando dados - EXERCICIO 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTvU0yOXuoK1eJktrW3CQ8p8kVKbZfX9

# Desafio: hora da prática

Chegou o momento de praticar! Vamos aplicar os conceitos aprendidos durante a aula a partir de algumas atividades. Solucione os problemas propostos através de códigos utilizando a base de dados disponibilizada no curso.

<br>

1.   Encontre os valores únicos das colunas "Nível 1 - Setor" e "Estado" para
identificar as atividades econômicas presentes na base de dados e se todos os Estados do Brasil estão presentes no DataFrame.
2.   Filtre o DataFrame somente com os dados dos Estados da região Sul do Brasil.

3. Filtre o DataFrame para exibir apenas os registros em que o campo "Nível 1 - Setor" seja igual a "Mudança de Uso da Terra e Floresta" e o campo "Estado" seja igual a "AM" (sigla para o Estado do Amazonas).

4. Encontre o valor máximo de emissão do ano de 2021 para os dados de "Agropecuária" no Estado do Pará.

<br>
"""

import pandas as pd

emissao_gases = pd.read_excel('/content/drive/MyDrive/Planilhas de estudo ALURA/SEEG10-BR_2022.10.27-FINAL.xlsx', sheet_name = 'GEE Estados')

emissao_gases

"""## Pronto, agora que preparamos o DF, vamos as questões:"""

# 01 - Encontre os valores únicos das colunas "Nível 1 - Setor" e "Estado" para identificar as atividades econômicas presentes na
# base de dados e se todos os Estados do Brasil estão presentes no DataFrame.

emissao_gases['Nível 1 - Setor'].unique()

emissao_gases['Estado'].unique()

# 02 - Filtre o DataFrame somente com os dados dos Estados da região Sul do Brasil.
emissao_gases_sul = emissao_gases[emissao_gases['Estado'].isin(['RS', 'SC', 'PR'])]
emissao_gases_sul

# 03 - Filtre o DataFrame para exibir apenas os registros em que o campo "Nível 1 - Setor" seja igual a
# "Mudança de Uso da Terra e Floresta" e o campo "Estado" seja igual a "AM" (sigla para o Estado do Amazonas).

emissao_gases[(emissao_gases['Nível 1 - Setor'] == 'Mudança de Uso da Terra e Floresta') & (emissao_gases['Estado'] == 'AM')]

# 04 - Encontre o valor máximo de emissão do ano de 2021 para os dados de "Agropecuária" no Estado do Pará.
emissao_gases.loc[(emissao_gases['Nível 1 - Setor'] == 'Agropecuária') & (emissao_gases['Estado'] == 'PA'), 2021].max()