# -*- coding: utf-8 -*-
"""Pandas: conhecendo a biblioteca Pandas: conhecendo a biblioteca

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOP4oSJ04ymxnHPKMpQewzNoJQYas7Px

# Conhecendo a base de dados (AULA 1)

Descrição

A base de dados que vamos utilizar para desenvolver o projeto é uma base com dados de diferentes tipos de imóveis do Rio de Janeiro, como apartamento, casas, comércios, dentre outros.

Nessa base, nós vamos encontrar os valores dos aluguéis de cada imóvel, condomínio, IPTU e também suas características, como: quantidade de quartos, suítes, vagas de garagem, etc.

Link para acessar a base de dados: aluguel.csv (https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv)

## Importando os dados
"""

import pandas as pd

url ='https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
pd.read_csv(url)

pd.read_csv(url, sep=';') # "sep=';' = Separa por ; os itens da tabela.

dados = pd.read_csv(url, sep=';') # "sep=';' = Separa por ; os itens da tabela.
dados

dados.head(10) # Mostra as 10 primeiras linhas da tabela.

dados.tail(10) # Mostra as 10 últimas linhas da tabela.

type(dados) # Mostra o tipo da tabela.

"""## Características gerais da base de dados"""

dados.shape # Mostra a quantidade de linhas e colunas da tabela.

dados.columns # Mostra as colunas da tabela.

dados.info()

dados['Tipo'] # Mostra apenas a coluna Tipo, os dados dessa coluna são texto, logo, object pode também conter strings.

dados[['Quartos', 'Valor']] # Mostra apenas as colunas Quartos e Valor.
                            # Os dados dessas colunas são do tipo decimal e inteiro, logo, INT representa os números inteiros
                            # e FLOAT representa os números decimais.

"""# Análise exploratória de dados (AULA 2)

## Qual o valor médio de aluguel por tipo de imóvel?
"""













"""## Removendo os imóveis comerciais"""















"""## Qual o percentual de cada tipo de imóvel na nossa base de dados?"""











"""### **Selecionando apenas os imóveis do tipo apartamento**"""





"""# Tratando e filtrando os dados

## Lidando com dados nulos
"""













"""## Removendo registros"""



















"""## Filtros

### **1. Apartamentos que possuem `1 quarto` e `aluguel menor que 1200`**
"""











"""### **2. `Apartamentos` que possuem pelo menos `2 quartos`, `aluguel menor que 3000` e `area maior que 70`**"""





"""## Salvando os dados"""

















"""# Manipulando os dados

## Criando colunas numéricas
"""







"""## Criando colunas categóricas"""









