# -*- coding: utf-8 -*-
"""Pandas: conhecendo a biblioteca - Desafio 3: bora praticar?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6R_UdfT_-Xr52--2aToqkyujYXpHTIY

# Desafio 3: bora praticar?

Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar alguns tratamentos e seleções utilizando um arquivo csv diferente: [alunos.csv](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv).

Esse arquivo é o mesmo utilizado para resolução dos desafios da aula 1 e possui dados referentes a alunos de um curso superior.

Com base nisso, solucione os problemas propostos abaixo utilizando os conhecimentos adquiridos até aqui.

<br>

1) Verifique se a base de dados possui dados nulos e, caso tenha, realize o tratamento desses dados nulos da forma que achar mais coerente com a situação.

2) Os alunos "Alice" e "Carlos", não fazem mais parte da turma. Sendo assim, remova-os da base de dados.

3) Aplique um filtro que selecione apenas os alunos que foram aprovados.

4) Salve o DataFrame que possui apenas os alunos aprovados em um arquivo csv chamado "alunos_aprovados.csv".

**Extra: Ao conferir as notas dos alunos aprovados, notamos que algumas notas estavam incorretas. As alunas que tiraram nota 7.0, na verdade, tinham um ponto extra que não foi contabilizado. Sendo assim, substitua as notas 7.0 da base de dados por 8.0. Dica: pesquise pelo método replace.**

Caso queira, deixo disponibilizado um [notebook para resolver os desafios](https://cdn3.gnarususercontent.com.br/2925-introducao-pandas/desafios.ipynb). Você pode baixá-lo e fazer upload no Google Drive ou direto no Google Colab para realizar os desafios dessa e das próximas aulas.

Se precisar de ajuda, na seção "Opinião do Instrutor" você pode encontrar algumas formas de resolver os desafios propostos acima.
"""

